2024-05-28 19:02:21,577 - MainThread - sqlmesh.core.config.connection - INFO - Creating new DuckDB adapter for data files: {'db.db'} (connection.py:294)
2024-05-28 19:02:21,894 - MainThread - sqlmesh.core.config.connection - INFO - Using existing DuckDB adapter due to overlapping data file: db.db (connection.py:290)
2024-05-28 19:02:27,654 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Listing data objects in schema db.sqlmesh__splice_case_study (evaluator.py:266)
2024-05-28 19:02:27,655 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT CURRENT_CATALOG() (base.py:1834)
2024-05-28 19:02:27,657 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT CURRENT_CATALOG() (base.py:1834)
2024-05-28 19:02:27,659 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT table_name AS name, table_schema AS schema, CASE table_type WHEN 'BASE TABLE' THEN 'table' WHEN 'VIEW' THEN 'view' WHEN 'LOCAL TEMPORARY' THEN 'table' END AS type FROM information_schema.tables WHERE table_schema = 'sqlmesh__splice_case_study' AND table_name IN ('splice_case_study__seed_model__84995534', 'splice_case_study__seed_model__84995534__temp', 'splice_case_study__view_model__2465641502__temp', 'splice_case_study__view_model__2465641502', 'splice_case_study__incremental_model__4290955', 'splice_case_study__incremental_model__4290955__temp') (base.py:1834)
2024-05-28 19:02:27,691 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Creating schema 'db.sqlmesh__splice_case_study' (evaluator.py:850)
2024-05-28 19:02:27,691 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE SCHEMA IF NOT EXISTS "db"."sqlmesh__splice_case_study" (base.py:1834)
2024-05-28 19:02:27,692 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Creating view 'db.sqlmesh__splice_case_study.splice_case_study__view_model__2465641502__temp' (evaluator.py:1587)
2024-05-28 19:02:27,707 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE VIEW "db"."sqlmesh__splice_case_study"."splice_case_study__view_model__2465641502__temp" AS WITH "total_customers_by_month" AS (SELECT COUNT(DISTINCT "user_id") AS "customer_count", "month" FROM "db"."sqlmesh_example"."seed_model" AS "seed_model" WHERE "customer_flag" = 1 GROUP BY "month"), "get_previous_months_data" AS (SELECT "user_id", LAG("month") OVER (PARTITION BY "user_id" ORDER BY "month") AS "previous_month", LAG("customer_flag") OVER (PARTITION BY "user_id" ORDER BY "month") AS "previous_customer_flag", "month" AS "current_month", "customer_flag" AS "current_customer_flag" FROM "db"."sqlmesh_example"."seed_model" AS "seed_model"), "customer_churn_count" AS (SELECT COUNT(DISTINCT "user_id") AS "overall_churn", "current_month" FROM "get_previous_months_data" AS "get_previous_months_data" WHERE DATE_DIFF('CURRENT_MONTH', "previous_month", "month") = 1 AND "previous_customer_flag" = 1 AND "current_customer_flag" = 0 GROUP BY "current_month"), "customer_return_count" AS (SELECT COUNT(DISTINCT "user_id") AS "overall_return", "current_month" FROM "get_previous_months_data" AS "get_previous_months_data" WHERE DATE_DIFF('CURRENT_MONTH', "previous_month", "month") = 1 AND "previous_customer_flag" = 0 AND "current_customer_flag" = 1 GROUP BY "current_month") SELECT "sm"."cohort_month" AS "cohort_month", "sm"."month" AS "month", DATE_DIFF('MONTH', "cohort_month", "month") + 1 AS "relative_month_number", "total"."customer_count" AS "overall_customers", "churn"."overall_churn" AS "overall_churn", "return"."overall_return" AS "overall_return" FROM "db"."sqlmesh_example"."seed_model" AS "sm" JOIN "total_customers_by_month" AS "total" ON "total"."month" = "sm"."month" JOIN "customer_churn_count" AS "churn" ON "churn"."current_month" = "sm"."month" JOIN "customer_return_count" AS "return" ON "return"."current_month" = "sm"."month" WHERE "month" BETWEEN '2023-06-01' AND '2024-02-01' (base.py:1834)
2024-05-28 19:02:27,719 - MainThread - sqlmesh.core.context - ERROR - Apply Failure: Traceback (most recent call last):
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/utils/concurrency.py", line 227, in sequential_apply_to_dag
    fn(node)
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/utils/concurrency.py", line 165, in <lambda>
    lambda s_id: fn(snapshots_by_id[s_id]),
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/core/snapshot/evaluator.py", line 293, in <lambda>
    lambda s: self._create_snapshot(
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/core/snapshot/evaluator.py", line 680, in _create_snapshot
    evaluation_strategy.create(
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/core/snapshot/evaluator.py", line 1588, in create
    self.adapter.create_view(
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/core/engine_adapter/shared.py", line 260, in internal_wrapper
    return func(*list_args, **kwargs)
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/core/engine_adapter/base.py", line 889, in create_view
    self.execute(
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/core/engine_adapter/base.py", line 1831, in execute
    self._execute(sql, **kwargs)
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/core/engine_adapter/base.py", line 1837, in _execute
    self.cursor.execute(sql, **kwargs)
duckdb.duckdb.CatalogException: Catalog Error: Table with name seed_model does not exist!
Did you mean "splice_case_study__dev.seed_model"?
LINE 1: ...erall_return" AS "overall_return" FROM "db"."sqlmesh_example"."seed_model" AS ...
                                                  ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/core/context.py", line 1172, in apply
    self._apply(plan, circuit_breaker)
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/core/context.py", line 1715, in _apply
    self._scheduler.create_plan_evaluator(self).evaluate(plan, circuit_breaker=circuit_breaker)
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/core/plan/evaluator.py", line 109, in evaluate
    self._push(plan, deployability_index_for_creation)
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/core/plan/evaluator.py", line 199, in _push
    self.snapshot_evaluator.create(
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/core/snapshot/evaluator.py", line 291, in create
    concurrent_apply_to_snapshots(
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/utils/concurrency.py", line 163, in concurrent_apply_to_snapshots
    return concurrent_apply_to_dag(
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/utils/concurrency.py", line 198, in concurrent_apply_to_dag
    return sequential_apply_to_dag(dag, fn, raise_on_error)
  File "/Users/alexanderstoner/dev/sqlmesh-prac/.env/lib/python3.9/site-packages/sqlmesh/utils/concurrency.py", line 230, in sequential_apply_to_dag
    raise NodeExecutionFailedError(node) from ex
sqlmesh.utils.concurrency.NodeExecutionFailedError: Execution failed for node SnapshotId<"db"."splice_case_study"."view_model": 2588214317>
 (context.py:1180)
2024-05-28 19:02:27,721 - MainThread - root - INFO - Shutting down the event dispatcher (dispatcher.py:159)
